=== TangoCS/TangoCS/Tango.TaskManager/TaskList.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TaskList">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Task" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Argument" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="Name" />
                      <xs:attribute type="xs:string" name="Value" />
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="Name"/>
            <xs:attribute type="xs:string" name="StartType"/>
            <xs:attribute type="xs:integer" name="Hours"/>
            <xs:attribute type="xs:integer" name="Minutes"/>
            <xs:attribute type="xs:string" name="Type"/>
            <xs:attribute type="xs:string" name="Method"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== TangoCS/TangoCS/Tango.TaskManager/TaskList.xml
<?xml version="1.0" encoding="utf-8" ?>
<TaskList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tasklist.xsd">
  <Task Name="Update" ThreadCount="1" StartType="Interval" Hours="0" Minutes="5" Type="Tango.TaskManager.WebClient" Method="Post">
    <Argument Name="url" Value="http://localhost:53885/longoperation/updatequeue?conn=231" />
    <Argument Name="userName" Value="" />
    <Argument Name="password" Value="" />
    <Argument Name="timeOut" Value="600" />
	  <Dictionary Name="data">
		  <Argument Name="system_id" Value="1,2" />
	  </Dictionary>
  </Task>
  <Task Name="Run" StartType="Interval" Hours="0" Minutes="5" Type="Tango.TaskManager.WebClient" Method="Post">
    <Argument Name="url" Value="http://localhost:53885/longoperation/runtask?conn=231" />
    <Argument Name="userName" Value="" />
    <Argument Name="password" Value="" />
    <Argument Name="timeOut" Value="600" />
  </Task>
</TaskList>
